import React from 'react';
import { formatNumber } from './App.jsx';
import FreightAILogo from './FreightAILogo.jsx';
import { generateDecisionSupport } from './decisionSupport.js';

function Unavailable({ title, result }) {
  const message = result?.status === 'rejected' ? result.reason?.message : result?.value?.dataDisclaimer;
  return <div className="message neutral-message"><strong>{title} unavailable.</strong><span>{message || 'This supplementary intelligence is not available. The core voyage assessment remains available.'}</span></div>;
}

function ResultSection({ number, title, children }) {
  return <section className="report-section" aria-labelledby={`section-${number}`}><div className="report-section-heading"><p className="section-kicker">{String(number).padStart(2, '0')} — {title}</p><h2 id={`section-${number}`}>{title}</h2></div>{children}</section>;
}

export default function VoyageResults({ user, onLogout, analysis, onBack }) {
  const { form, recommendation, compatibility, intelligence } = analysis;
  const topRecommendation = recommendation.recommendations[0];
  const lane = intelligence.tradeLane.status === 'fulfilled' ? intelligence.tradeLane.value : null;
  const market = intelligence.market.status === 'fulfilled' ? intelligence.market.value : null;
  const forecast = intelligence.forecast.status === 'fulfilled' ? intelligence.forecast.value : null;
  const status = compatibility.compatible ? 'Compatible' : 'Not compatible';
  const support = generateDecisionSupport(analysis);
  return <main className="app-shell results-shell">
    <header className="site-header"><FreightAILogo className="dashboard-logo" /><div className="user-menu"><span>{user.name}<small>{user.email}</small></span><button type="button" onClick={onLogout}>Log out</button></div></header>
    <article className="voyage-report">
      <div className="report-hero"><button className="back-button" type="button" onClick={onBack}>← Back to Voyage Planning</button><p className="eyebrow">FreightAI</p><h1>Voyage Analysis</h1><p className="report-route">{form.originPort} <span aria-hidden="true">→</span> {form.destinationPort}</p><p>Cargo: <strong>{formatNumber(form.cargoQuantity)} MT</strong></p></div>
      <ResultSection number={1} title="Voyage Overview"><dl className="overview-grid"><div><dt>Origin</dt><dd>{form.originPort}</dd></div><div><dt>Destination</dt><dd>{form.destinationPort}</dd></div><div><dt>Cargo</dt><dd>{formatNumber(form.cargoQuantity)} MT</dd></div><div><dt>Assessment vessel</dt><dd>{form.vesselType}</dd></div></dl></ResultSection>
      <ResultSection number={2} title="Vessel Recommendation">
        {topRecommendation ? <><div className="recommendation-hero"><span>Recommended vessel</span><strong>{topRecommendation.vesselType}</strong><p>{topRecommendation.suitability === 'TYPICAL_CAPACITY_MATCH' ? 'Typical capacity match for the selected cargo.' : 'Oversized capacity match for the selected cargo.'}</p></div><div className="recommendation-list">{recommendation.recommendations.map((vessel) => <article className={`vessel-card ${vessel.rank === 1 ? 'top-recommendation' : ''}`} key={vessel.vesselType}><div className="vessel-title"><span className="rank">#{vessel.rank}</span><div><h3>{vessel.vesselType}</h3><p>{vessel.suitability === 'TYPICAL_CAPACITY_MATCH' ? 'Typical capacity match' : 'Oversized capacity match'}</p></div></div><dl><div><dt>Typical capacity</dt><dd>{formatNumber(vessel.minimumTypicalCargoCapacity)}–{formatNumber(vessel.maximumTypicalCargoCapacity)} t</dd></div><div><dt>Unused capacity</dt><dd>{formatNumber(vessel.capacitySurplus)} t</dd></div><div><dt>Draft / LOA / Beam</dt><dd>{vessel.typicalDraft} m / {vessel.typicalLOA} m / {vessel.typicalBeam} m</dd></div></dl></article>)}</div></> : <Unavailable title="Vessel recommendation" />}
        <p className="disclaimer">{recommendation.dataDisclaimer}</p>
      </ResultSection>
      <ResultSection number={3} title="Port Compatibility"><div className="result-heading"><h3>{compatibility.originPort.portName} to {compatibility.destinationPort.portName}</h3><span className={`status-badge ${compatibility.compatible ? 'compatible' : 'incompatible'}`}>{status}</span></div><p className="assessment-detail">Assessment vessel: <strong>{compatibility.vesselType.vesselType}</strong>. Destination limits are shown below.</p><div className="constraint-grid"><div><span>Draft</span><strong>{compatibility.vesselType.typicalDraft} m / {compatibility.destinationPort.maximumDraft} m</strong></div><div><span>LOA</span><strong>{compatibility.vesselType.typicalLOA} m / {compatibility.destinationPort.maximumLOA} m</strong></div><div><span>Beam</span><strong>{compatibility.vesselType.typicalBeam} m / {compatibility.destinationPort.maximumBeam} m</strong></div></div>{compatibility.failedConstraints.length > 0 && <p className="failure-note">Failed: {compatibility.failedConstraints.map((constraint) => constraint.constraint.replace('maximum', '')).join(', ')}.</p>}<p className="subtle-note">{compatibility.reasons?.join(' ')}</p><p className="disclaimer">{compatibility.originPortConstraintsEvaluated ? 'Origin constraints were evaluated.' : 'Destination-side dimensional constraints only: origin, berth, tide, terminal, weather, clearance, and operational constraints are not comprehensively evaluated.'}</p></ResultSection>
      <ResultSection number={4} title="Trade Lane Intelligence">{lane ? <><p className="lane-route">{lane.laneName}</p>{lane.isDetailedLaneDataAvailable === false ? <div className="route-profile"><strong>Estimated route profile</strong><dl className="overview-grid"><div><dt>Trade direction</dt><dd>{lane.routeProfile?.tradeDirection}</dd></div><div><dt>Route countries</dt><dd>{lane.routeProfile?.originCountry} → {lane.routeProfile?.destinationCountry}</dd></div></dl></div> : <dl className="overview-grid"><div><dt>Distance</dt><dd>{formatNumber(lane.distanceNm)} nm</dd></div><div><dt>Estimated transit</dt><dd>{lane.estimatedTransitDays} days</dd></div><div><dt>Preferred vessel types</dt><dd>{lane.preferredVesselTypes?.join(', ')}</dd></div><div><dt>Cargo categories</dt><dd>{lane.cargoTypes?.join(', ')}</dd></div></dl>}<p className="disclaimer">{lane.dataClassification}: {lane.dataDisclaimer}</p></> : <Unavailable title="Trade Lane Intelligence" result={intelligence.tradeLane} />}</ResultSection>
      <ResultSection number={5} title="Freight & Market Intelligence">{market?.isMarketDataAvailable ? <><div className="market-rate"><span>Indicative freight market signal</span><strong>{formatNumber(market.indicativeFreightRate)} {market.freightRateUnit}</strong></div><dl className="overview-grid"><div><dt>Market direction</dt><dd>{market.marketDirection}</dd></div><div><dt>Market strength</dt><dd>{market.marketStrength}</dd></div><div><dt>Demand signal</dt><dd>{market.demandSignal}</dd></div><div><dt>Vessel supply</dt><dd>{market.vesselSupplySignal}</dd></div><div><dt>Market status</dt><dd>{market.marketStatus}</dd></div><div><dt>Snapshot vessel</dt><dd>{market.vesselType}</dd></div></dl><p className="subtle-note">{market.commentary}</p><p className="disclaimer">{market.dataClassification}: {market.dataDisclaimer}</p></> : <Unavailable title="Freight & Market Intelligence" result={intelligence.market} />}</ResultSection>
      <ResultSection number={6} title="Market-wide BDI Outlook">{forecast?.isForecastAvailable ? <><p className="subtle-note">Voyage context: {form.originPort} → {form.destinationPort}. This is a market-wide dry bulk outlook, not a route freight forecast.</p><div className="forecast-values"><div className="forecast-value"><span className="forecast-value-label">Current BDI</span><strong>{formatNumber(forecast.currentBdi)}</strong></div><span className="forecast-arrow" aria-hidden="true">→</span><div className="forecast-value"><span className="forecast-value-label">Forecast BDI</span><strong>{formatNumber(forecast.forecastBdi, { maximumFractionDigits: 2 })}</strong></div></div><dl className="overview-grid"><div><dt>Expected change</dt><dd>{forecast.percentageChange > 0 ? '+' : ''}{forecast.percentageChange.toFixed(2)}%</dd></div><div><dt>Absolute change</dt><dd>{forecast.absoluteChange > 0 ? '+' : ''}{forecast.absoluteChange.toFixed(2)}</dd></div><div><dt>Direction</dt><dd>{forecast.direction}</dd></div><div><dt>Horizon</dt><dd>{forecast.forecastHorizonObservations} observations</dd></div><div><dt>Model</dt><dd>{forecast.model}</dd></div><div><dt>Feature count</dt><dd>{forecast.featureCount}</dd></div></dl><p className="disclaimer">{forecast.dataClassification}: {forecast.dataDisclaimer}</p></> : <Unavailable title="Market-wide BDI Outlook" result={intelligence.forecast} />}</ResultSection>
      <ResultSection number={7} title="Decision Support Summary"><div className={`decision-card decision-${support.decision.toLowerCase()}`}><p className="section-kicker">Recommended action</p><div className="decision-title"><strong>{support.label}</strong><span>Decision confidence: {support.confidence}</span></div><p>{support.summary}</p><p className="decision-score">Rule-based decision score: {support.score}/100</p><div className="decision-columns"><div><h3>Why</h3><ul>{support.reasons.map((reason) => <li key={reason}>{reason}</li>)}</ul></div><div><h3>Cautions & limitations</h3><ul>{support.cautionSignals.map((signal) => <li key={signal}>{signal}</li>)}</ul></div></div>{support.blockingIssues.length > 0 && <div className="decision-blockers"><h3>Blocking issues</h3><ul>{support.blockingIssues.map((issue) => <li key={issue}>{issue}</li>)}</ul></div>}<div className="decision-action"><h3>Suggested next action</h3><p>{support.recommendedAction}</p></div><p className="disclaimer">{support.disclaimer}</p></div><button className="back-button" type="button" onClick={onBack}>← Back to Voyage Planning</button></ResultSection>
    </article>
    <footer>FreightAI prototype · Decisions use illustrative demo data and are not operational chartering advice.</footer>
  </main>;
}
